### ISSUE TITLE
Neosnippet does not detect neosnippet-snippets

### ISSUE THREAD

**Issue by AA1999** [Shougo/neosnippet-snippets#197] opened 2021-10-01 18:19 UTC
Upon going to insert mode I get this
![image](https://user-images.githubusercontent.com/14325650/135668267-68660a9f-2a3e-41cb-8f26-281ee27c7386.png)

I'm using packer.nvim (on neo-vim nightly) and this is my plugins.lua:
```
return require('packer').startup(function(use)
use 'wbthomason/packer.nvim'
use 'sheerun/vim-polyglot'
use 'dense-analysis/ale'
use 'relastle/bluewery.vim'
use 'andymass/vim-matchup'
use 'tpope/vim-dispatch'
use 'tpope/vim-surround'
use 'andweeb/presence.nvim'
use 'sakhnik/nvim-gdb'
use 'glepnir/indent-guides.nvim'
use {'ms-jpq/chadtree', run = 'python3 -m chadtree deps'}
use 'glepnir/prodoc.nvim'
use 'pwntester/octo.nvim'
use 'scrooloose/nerdcommenter'
use 'mattn/emmet-vim'
use {'neoclide/coc.nvim', branch = 'release'}
use 'eslint/eslint'
use {'Shougo/deoplete.nvim', run = ':UpdateRemotePlugins'} 
use 'Shougo/neosnippet.vim'
use 'roxma/nvim-yarp'
use 'roxma/vim-hug-neovim-rpc' 
use 'Shougo/neosnippet-snippets'	 
use {'autozimu/LanguageClient-neovim', branch = 'next', run = 'powershell -executionpolicy bypass -File install.ps1'}
use 'junegunn/fzf'
end)
```

**Comment by Shougo** [comment] 2021-10-02 01:12
Sorry.  I don't support your config.
Because I don't test it.
I will support if you reproduce it without packer.nvim.

Please read other issues.  Closing.

**Closed by Shougo** 2021-10-02 01:12 UTC
